packages:
  - 'packages/*'
  - 'apps/*'

catalog:
  '@supabase/supabase-js': ^2.58.0
  '@tanstack/react-query': ^5.83.0
  'react': ^18.3.1
  'react-dom': ^18.3.1
  'typescript': ^5.8.3
  'vite': ^7.1.11
  'vitest': ^3.2.4
  'rxjs': ^7.8.1
