name: Publish Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }} – Ship-safety + Pagination v1 + A+ Security Review
          body_path: deliverables/RELEASE_v1.3.0.md
          files: |
            deliverables/QUICK_SHIP_CARD_2025-10-21.md
            review/SECURITY_REVIEW_2025-10-21.md
          fail_on_unmatched_files: true
